/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package backup.dats;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author fernando
 */
public class FrmConfig extends javax.swing.JFrame {

    /**
     * Creates new form FrmConfig
     */
    public FrmConfig() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grRadioCompactacao = new javax.swing.ButtonGroup();
        grRadioModo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radioBaixa = new javax.swing.JRadioButton();
        radioNormal = new javax.swing.JRadioButton();
        radioAlta = new javax.swing.JRadioButton();
        radioUltra = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        txtExecutaAntes = new javax.swing.JTextField();
        btLoadExecutaAntes = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtExecutaDepois = new javax.swing.JTextField();
        btLoadExecutaDepois = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btSalvaConfig = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        radioDat = new javax.swing.JRadioButton();
        radioPost = new javax.swing.JRadioButton();
        btConfiguraPost = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações do Backup");
        setLocationByPlatform(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de compactação"));

        grRadioCompactacao.add(radioBaixa);
        radioBaixa.setText("Baixa (Rápida)");

        grRadioCompactacao.add(radioNormal);
        radioNormal.setText("Normal");

        grRadioCompactacao.add(radioAlta);
        radioAlta.setText("Alta");

        grRadioCompactacao.add(radioUltra);
        radioUltra.setText("Ultra (Lenta)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioBaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioUltra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(radioBaixa)
                .addComponent(radioNormal)
                .addComponent(radioAlta)
                .addComponent(radioUltra))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bat executar antes do backup"));

        btLoadExecutaAntes.setText("Buscar");
        btLoadExecutaAntes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoadExecutaAntesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtExecutaAntes, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLoadExecutaAntes))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtExecutaAntes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btLoadExecutaAntes))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Bat executar depois do backup"));

        btLoadExecutaDepois.setText("Buscar");
        btLoadExecutaDepois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoadExecutaDepoisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtExecutaDepois, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLoadExecutaDepois)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtExecutaDepois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btLoadExecutaDepois))
        );

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btSalvaConfig.setText("Salvar");
        btSalvaConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvaConfigActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Banco de Dados"));

        grRadioModo.add(radioDat);
        radioDat.setSelected(true);
        radioDat.setText("Dat");
        radioDat.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioDatStateChanged(evt);
            }
        });
        radioDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDatActionPerformed(evt);
            }
        });

        grRadioModo.add(radioPost);
        radioPost.setText("PostgreSQL");

        btConfiguraPost.setText("Dados PostgreSQL");
        btConfiguraPost.setToolTipText("");
        btConfiguraPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfiguraPostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioDat)
                .addGap(10, 10, 10)
                .addComponent(radioPost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConfiguraPost)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(radioDat)
                .addComponent(radioPost)
                .addComponent(btConfiguraPost))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSalvaConfig)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btSalvaConfig))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvaConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvaConfigActionPerformed
        try {
            // TODO add your handling code here:
            Configuracoes cfg = new Configuracoes();
            cfg.setPropriedade("executa_antes", txtExecutaAntes.getText());
            cfg.setPropriedade("executa_depois", txtExecutaDepois.getText());
            cfg.setPropriedade("compactacao", String.valueOf(getTipoCompactacao()));
            cfg.setPropriedade("modo", setTipoDados());
            fecharForm();
        } catch (FileNotFoundException | UnsupportedEncodingException ex) {
            Logger.getLogger(FrmConfig.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FrmConfig.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btSalvaConfigActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fecharForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            Configuracoes cfg = new Configuracoes();
            txtExecutaAntes.setText(cfg.getPropriedade("executa_antes"));
            txtExecutaDepois.setText(cfg.getPropriedade("executa_depois"));
            setTipoCompactacao(cfg.getPropriedade("compactacao"));
            getTipoDados(cfg.getPropriedade("modo"));
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(FrmConfig.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FrmConfig.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formWindowOpened

    private void btLoadExecutaAntesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoadExecutaAntesActionPerformed
        // TODO add your handling code here:
        selecionaExecutavel("antes");
    }//GEN-LAST:event_btLoadExecutaAntesActionPerformed

    private void btLoadExecutaDepoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoadExecutaDepoisActionPerformed
        // TODO add your handling code here:
        selecionaExecutavel("depois");
    }//GEN-LAST:event_btLoadExecutaDepoisActionPerformed

    private void radioDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDatActionPerformed

    private void radioDatStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioDatStateChanged
        // TODO add your handling code here:
        if (radioDat.isSelected()) {
            btConfiguraPost.setEnabled(false);
        } else {
            btConfiguraPost.setEnabled(true);
        }
    }//GEN-LAST:event_radioDatStateChanged

    private void btConfiguraPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfiguraPostActionPerformed
        // TODO add your handling code here:
        FrmPost frm = new FrmPost();
        frm.setVisible(true);
    }//GEN-LAST:event_btConfiguraPostActionPerformed
    private void fecharForm() {
        setVisible(false);
    }

    private void selecionaExecutavel(String local) {
        JFileChooser j = new JFileChooser(new File("."));
        j.setDialogType(JFileChooser.OPEN_DIALOG);
        j.setDialogTitle("Carregar executável");
        j.setApproveButtonText("Selecionar");
        j.setFileFilter(new FileNameExtensionFilter("Arquivo BAT", "BAT"));
        Integer opt = j.showSaveDialog(this);
        if (opt == 0) {
            if (!j.getSelectedFile().getName().contains(" ")) {
                if (local.equals("antes")) {
                    txtExecutaAntes.setText(j.getSelectedFile().getAbsolutePath());
                } else {
                    txtExecutaDepois.setText(j.getSelectedFile().getAbsolutePath());
                }
            } else {
                JOptionPane.showMessageDialog(this, "O nome do arquivo não pode conter espaços");
            }
        }
    }

    private String setTipoDados() {
        if (radioDat.isSelected()) {
            return "dat";
        } else if (radioPost.isSelected()) {
            return "post";
        } else {
            return "dat";
        }
    }

    private void getTipoDados(String tipo) {
        if ("post".equals(tipo)) {
            radioPost.setSelected(true);
        } else {
            radioDat.setSelected(true);
            btConfiguraPost.setEnabled(false);
        }
    }

    private int getTipoCompactacao() {
        if (radioBaixa.isSelected()) {
            return 1;
        } else if (radioNormal.isSelected()) {
            return 5;
        } else if (radioAlta.isSelected()) {
            return 7;
        } else if (radioUltra.isSelected()) {
            return 9;
        } else {
            return 3;
        }
    }

    private void setTipoCompactacao(String valor) {
        if (null != valor) {
            switch (valor) {
                case "1":
                    radioBaixa.setSelected(true);
                    break;
                case "5":
                    radioNormal.setSelected(true);
                    break;
                case "7":
                    radioAlta.setSelected(true);
                    break;
                case "9":
                    radioUltra.setSelected(true);
                    break;
                default:
                    break;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConfig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfiguraPost;
    private javax.swing.JButton btLoadExecutaAntes;
    private javax.swing.JButton btLoadExecutaDepois;
    private javax.swing.JButton btSalvaConfig;
    private javax.swing.ButtonGroup grRadioCompactacao;
    private javax.swing.ButtonGroup grRadioModo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton radioAlta;
    private javax.swing.JRadioButton radioBaixa;
    private javax.swing.JRadioButton radioDat;
    private javax.swing.JRadioButton radioNormal;
    private javax.swing.JRadioButton radioPost;
    private javax.swing.JRadioButton radioUltra;
    private javax.swing.JTextField txtExecutaAntes;
    private javax.swing.JTextField txtExecutaDepois;
    // End of variables declaration//GEN-END:variables
}
