/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package backup.dats;

import java.awt.Desktop;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author fernando
 */
public class FrmConfig extends javax.swing.JFrame {

    /**
     * Creates new form FrmConfig
     */
    Log logger;

    public FrmConfig() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grRadioCompactacao = new javax.swing.ButtonGroup();
        grRadioModo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radioBaixa = new javax.swing.JRadioButton();
        radioNormal = new javax.swing.JRadioButton();
        radioAlta = new javax.swing.JRadioButton();
        radioUltra = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        txtExecutaAntes = new javax.swing.JTextField();
        btLoadExecutaAntes = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtExecutaDepois = new javax.swing.JTextField();
        btLoadExecutaDepois = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btSalvaConfig = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btConfiguraPost = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btDadosFtp = new javax.swing.JButton();
        ckFtp = new javax.swing.JCheckBox();
        ckDesligaPC = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        btAgendar = new javax.swing.JButton();
        ckBkFacil = new javax.swing.JCheckBox();
        btNomeArquivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btArquivosTemp = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDiasMantem = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações do Backup");
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de compactação"));

        grRadioCompactacao.add(radioBaixa);
        radioBaixa.setText("Baixa (Rápida)");
        radioBaixa.setToolTipText("Resulta em um arquivo de tamanho maior, porém o tempo de compactação é menor");

        grRadioCompactacao.add(radioNormal);
        radioNormal.setText("Normal");

        grRadioCompactacao.add(radioAlta);
        radioAlta.setSelected(true);
        radioAlta.setText("Alta");

        grRadioCompactacao.add(radioUltra);
        radioUltra.setText("Ultra (Lenta)");
        radioUltra.setToolTipText("Resulta em um arquivo de tamanho menor, porém o tempo de compactação é maior");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(radioBaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioUltra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(radioBaixa)
                .addComponent(radioNormal)
                .addComponent(radioAlta)
                .addComponent(radioUltra))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bat executar antes do backup"));

        txtExecutaAntes.setToolTipText("Selecione um arquivo .bat para executar antes de copiar os arquivos");

        btLoadExecutaAntes.setText("Buscar");
        btLoadExecutaAntes.setToolTipText("Selecione um arquivo .bat para executar antes de copiar os arquivos");
        btLoadExecutaAntes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoadExecutaAntesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtExecutaAntes, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLoadExecutaAntes))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtExecutaAntes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btLoadExecutaAntes))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Bat executar depois do backup"));

        txtExecutaDepois.setToolTipText("Selecione um arquivo .bat para executar depois de copiar os arquivos");

        btLoadExecutaDepois.setText("Buscar");
        btLoadExecutaDepois.setToolTipText("Selecione um arquivo .bat para executar depois de copiar os arquivos");
        btLoadExecutaDepois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoadExecutaDepoisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtExecutaDepois, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLoadExecutaDepois)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtExecutaDepois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btLoadExecutaDepois))
        );

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btSalvaConfig.setBackground(new java.awt.Color(1, 109, 187));
        btSalvaConfig.setForeground(new java.awt.Color(255, 255, 255));
        btSalvaConfig.setText("Salvar configurações");
        btSalvaConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvaConfigActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Backup PostgreSQL"));

        btConfiguraPost.setText("Dados PostgreSQL");
        btConfiguraPost.setToolTipText("Inclua os dados para conexão com o PostgreSQL");
        btConfiguraPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfiguraPostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btConfiguraPost)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btConfiguraPost, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("FTP"));

        btDadosFtp.setText("Dados");
        btDadosFtp.setToolTipText("Inclua os dados de conexão com o servidor de FTP");
        btDadosFtp.setEnabled(false);
        btDadosFtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDadosFtpActionPerformed(evt);
            }
        });

        ckFtp.setText("Backup FTP");
        ckFtp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckFtpMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ckFtpMouseReleased(evt);
            }
        });
        ckFtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckFtpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(ckFtp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDadosFtp)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btDadosFtp)
                .addComponent(ckFtp))
        );

        ckDesligaPC.setText("Desligar o computador ao terminar o backup");
        ckDesligaPC.setToolTipText("Desligar o computador quando terminar de fazer o backup");
        ckDesligaPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckDesligaPCMouseClicked(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Backup Automático"));

        btAgendar.setText("Agendar");
        btAgendar.setToolTipText("Configurar agendamento de backup");
        btAgendar.setEnabled(false);
        btAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgendarActionPerformed(evt);
            }
        });

        ckBkFacil.setText("Backup automático");
        ckBkFacil.setToolTipText("Com esse modo ativo o backup irá iniciar automáticamente ao executar o programa");
        ckBkFacil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckBkFacilMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ckBkFacilMouseReleased(evt);
            }
        });
        ckBkFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckBkFacilActionPerformed(evt);
            }
        });

        btNomeArquivo.setText("Nome arquivo");
        btNomeArquivo.setToolTipText("Definir nome do arquivo gerado no backup");
        btNomeArquivo.setEnabled(false);
        btNomeArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNomeArquivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ckBkFacil)
                .addGap(12, 12, 12)
                .addComponent(btAgendar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btNomeArquivo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btAgendar)
                .addComponent(ckBkFacil)
                .addComponent(btNomeArquivo))
        );

        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Visualizar Log");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Arquivos Temporários"));

        btArquivosTemp.setText("Pasta temporária");
        btArquivosTemp.setToolTipText("Definir onde serão copiados os arquivos temporários");
        btArquivosTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArquivosTempActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btArquivosTemp)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btArquivosTemp, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Apagar backups"));

        jLabel2.setText("Manter backups por");

        jLabel3.setText("dias");

        txtDiasMantem.setModel(new javax.swing.SpinnerNumberModel(15, 1, 999, 1));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiasMantem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addComponent(txtDiasMantem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ckDesligaPC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSalvaConfig)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckDesligaPC)
                    .addComponent(jLabel1))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btSalvaConfig))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvaConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvaConfigActionPerformed
        try {
            logger = new Log();
            // TODO add your handling code here:
            Configuracoes cfg = new Configuracoes();
            cfg.setPropriedade("manter_arquivos", txtDiasMantem.getValue().toString());
            cfg.setPropriedade("executa_antes", txtExecutaAntes.getText());
            cfg.setPropriedade("executa_depois", txtExecutaDepois.getText());
            cfg.setPropriedade("compactacao", String.valueOf(getTipoCompactacao()));
            cfg.setPropriedade("backup_facil", String.valueOf(ckBkFacil.isSelected()));
            cfg.setPropriedade("desliga_pc", String.valueOf(ckDesligaPC.isSelected()));
            cfg.setPropriedade("ftp_backup", String.valueOf(ckFtp.isSelected()));
            fecharForm();
         
        } catch (FileNotFoundException | UnsupportedEncodingException ex) {
            logger.erro(ex.getMessage());
        } catch (IOException ex) {
            logger.erro(ex.getMessage());
        }

    }//GEN-LAST:event_btSalvaConfigActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fecharForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Configuracoes cfg = new Configuracoes();
            txtDiasMantem.setValue(Integer.valueOf(cfg.getPropriedade("manter_arquivos")));
            txtExecutaAntes.setText(cfg.getPropriedade("executa_antes"));
            txtExecutaDepois.setText(cfg.getPropriedade("executa_depois"));
            setTipoCompactacao(cfg.getPropriedade("compactacao"));
            ckBkFacil.setSelected(Boolean.valueOf(cfg.getPropriedade("backup_facil")));
            ckDesligaPC.setSelected(Boolean.valueOf(cfg.getPropriedade("desliga_pc")));
            ckFtp.setSelected(Boolean.valueOf(cfg.getPropriedade("ftp_backup")));
            btDadosFtp.setEnabled(ckFtp.isSelected());
            btAgendar.setEnabled(ckBkFacil.isSelected());
            btNomeArquivo.setEnabled(ckBkFacil.isSelected());
        } catch (UnsupportedEncodingException ex) {
            logger.erro(ex.getMessage());
        } catch (IOException ex) {
            logger.erro(ex.getMessage());
        }

    }//GEN-LAST:event_formWindowOpened

    private void btLoadExecutaAntesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoadExecutaAntesActionPerformed
        selecionaExecutavel("antes");
    }//GEN-LAST:event_btLoadExecutaAntesActionPerformed

    private void btLoadExecutaDepoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoadExecutaDepoisActionPerformed
        selecionaExecutavel("depois");
    }//GEN-LAST:event_btLoadExecutaDepoisActionPerformed

    private void btConfiguraPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfiguraPostActionPerformed
        try {
            // TODO add your handling code here:
            FrmPost frm = new FrmPost();
            frm.setIconImage(ImageIO.read(BackupDats.class.getResource("res/icon.png")));
            frm.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FrmConfig.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btConfiguraPostActionPerformed

    private void btDadosFtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDadosFtpActionPerformed
        try {
            // TODO add your handling code here:
            FrmFtp frm = new FrmFtp();
            frm.setIconImage(ImageIO.read(BackupDats.class.getResource("res/icon.png")));
            frm.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FrmConfig.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btDadosFtpActionPerformed

    private void ckFtpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckFtpMouseClicked
        // TODO add your handling code here:
        if (ckFtp.isSelected()) {
            btDadosFtp.setEnabled(true);
        } else {
            btDadosFtp.setEnabled(false);
        }
    }//GEN-LAST:event_ckFtpMouseClicked

    private void ckFtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckFtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckFtpActionPerformed

    private void ckDesligaPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckDesligaPCMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ckDesligaPCMouseClicked

    private void btAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgendarActionPerformed
        try {
            // TODO add your handling code here:
            FrmAgendar frm = new FrmAgendar();
            frm.setIconImage(ImageIO.read(BackupDats.class.getResource("res/icon.png")));
            frm.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FrmConfig.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAgendarActionPerformed

    private void ckBkFacilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckBkFacilMouseClicked

    }//GEN-LAST:event_ckBkFacilMouseClicked

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        try {
            Desktop.getDesktop().open(new File("MakitoBackupLogs"));
        } catch (IOException ex) {
            Logger.getLogger(FrmConfig.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MouseReleased

    private void btNomeArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNomeArquivoActionPerformed
        try {
            FrmNomeArquivo frm = new FrmNomeArquivo();
            frm.setIconImage(ImageIO.read(BackupDats.class.getResource("res/icon.png")));
            frm.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FrmConfig.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btNomeArquivoActionPerformed

    private void btArquivosTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArquivosTempActionPerformed
        try {
            // TODO add your handling code here:
            FrmArquivosTemp frm = new FrmArquivosTemp();
            frm.setIconImage(ImageIO.read(BackupDats.class.getResource("res/icon.png")));
            frm.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FrmConfig.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btArquivosTempActionPerformed

    private void ckBkFacilMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckBkFacilMouseReleased
        btAgendar.setEnabled(ckBkFacil.isSelected());
        btNomeArquivo.setEnabled(ckBkFacil.isSelected());
        if (ckBkFacil.isSelected()) {
            verificaConfigBackup();
        }
    }//GEN-LAST:event_ckBkFacilMouseReleased

    private void ckFtpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckFtpMouseReleased
        if (ckFtp.isSelected()) {
            btDadosFtp.setEnabled(true);
        } else {
            btDadosFtp.setEnabled(false);
        }
    }//GEN-LAST:event_ckFtpMouseReleased

    private void ckBkFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckBkFacilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckBkFacilActionPerformed
    private void fecharForm() {
        setVisible(false);
    }

    private void verificaConfigBackup() {
        try {
            Configuracoes cfg = new Configuracoes();
            String pastaOrigem = cfg.getPropriedade("pasta_origem");
            String pastaDestino = cfg.getPropriedade("pasta_destino");
            if (pastaOrigem.equals("")) {
                String pathAtual = new File(".").getCanonicalPath();
                int dialogResult = JOptionPane.showConfirmDialog(null, "<html>A pasta atual é <b>" + pathAtual + "</b><br>Está é a pasta do sistema?</html>", "Definir pasta do sistema", JOptionPane.YES_NO_OPTION);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    cfg.setPropriedade("pasta_origem", pathAtual);
                } else {
                    JOptionPane.showMessageDialog(null, "<html>Informe qual é a <b>pasta do sistema</b></html>");
                    pastaOrigem = selecionaPasta();
                    if (new File(pastaOrigem).isDirectory()) {
                        cfg.setPropriedade("pasta_origem", pastaOrigem);
                    } else {
                        JOptionPane.showMessageDialog(null, "Selecione uma pasta válida");
                        ckBkFacil.setSelected(false);
                    }
                }
            }

            if (pastaDestino.equals("")) {
                JOptionPane.showMessageDialog(null, "<html>Informe onde o backup será salvo</html>");
                selecionaDestinos();
            }
        } catch (UnsupportedEncodingException ex) {
            logger.erro(ex.getMessage());
        } catch (IOException ex) {
            logger.erro(ex.getMessage());
        }
    }

    private void selecionaDestinos() {
        try {
            FrmDestinos frm = new FrmDestinos();
            frm.setIconImage(ImageIO.read(BackupDats.class.getResource("res/icon.png")));
            frm.setVisible(true);
            frm.addComponentListener(new ComponentAdapter() {
                public void componentHidden(ComponentEvent e) {
                    try {
                        Configuracoes cfg = new Configuracoes();
                        if (cfg.getPropriedade("pasta_destino").equals("")) {
                            JOptionPane.showMessageDialog(null, "<html>Selecione ao menos um local de destino</html>");
                            selecionaDestinos();
                        }
                    } catch (UnsupportedEncodingException ex) {
                        Logger.getLogger(FrmConfig.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(FrmConfig.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
        } catch (IOException ex) {
            Logger.getLogger(FrmConfig.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private String selecionaPasta() {
        JFileChooser j = new JFileChooser(new File("."));
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        j.setDialogTitle("Selecione uma pasta");
        j.setApproveButtonText("Selecionar Pasta");
        j.setAcceptAllFileFilterUsed(false);
        Integer opt = j.showOpenDialog(this);
        if (opt == 0) {
            return j.getSelectedFile().getAbsolutePath();
        } else {
            return "";
        }
    }

    private void selecionaExecutavel(String local) {
        JFileChooser j = new JFileChooser(new File("."));
        j.setDialogType(JFileChooser.OPEN_DIALOG);
        j.setDialogTitle("Carregar executável");
        j.setApproveButtonText("Selecionar");
        j.setFileFilter(new FileNameExtensionFilter("Arquivo BAT", "BAT"));
        Integer opt = j.showSaveDialog(this);
        if (opt == 0) {
            if (!j.getSelectedFile().getName().contains(" ")) {
                if (local.equals("antes")) {
                    txtExecutaAntes.setText(j.getSelectedFile().getAbsolutePath());
                } else {
                    txtExecutaDepois.setText(j.getSelectedFile().getAbsolutePath());
                }
            } else {
                JOptionPane.showMessageDialog(this, "O nome do arquivo não pode conter espaços");
            }
        }
    }

    private int getTipoCompactacao() {
        if (radioBaixa.isSelected()) {
            return 1;
        } else if (radioNormal.isSelected()) {
            return 5;
        } else if (radioAlta.isSelected()) {
            return 7;
        } else if (radioUltra.isSelected()) {
            return 9;
        } else {
            return 3;
        }
    }

    private void setTipoCompactacao(String valor) {
        if (null != valor) {
            switch (valor) {
                case "1":
                    radioBaixa.setSelected(true);
                    break;
                case "5":
                    radioNormal.setSelected(true);
                    break;
                case "7":
                    radioAlta.setSelected(true);
                    break;
                case "9":
                    radioUltra.setSelected(true);
                    break;
                default:
                    break;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConfig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgendar;
    private javax.swing.JButton btArquivosTemp;
    private javax.swing.JButton btConfiguraPost;
    private javax.swing.JButton btDadosFtp;
    private javax.swing.JButton btLoadExecutaAntes;
    private javax.swing.JButton btLoadExecutaDepois;
    private javax.swing.JButton btNomeArquivo;
    private javax.swing.JButton btSalvaConfig;
    private javax.swing.JCheckBox ckBkFacil;
    private javax.swing.JCheckBox ckDesligaPC;
    private javax.swing.JCheckBox ckFtp;
    private javax.swing.ButtonGroup grRadioCompactacao;
    private javax.swing.ButtonGroup grRadioModo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton radioAlta;
    private javax.swing.JRadioButton radioBaixa;
    private javax.swing.JRadioButton radioNormal;
    private javax.swing.JRadioButton radioUltra;
    private javax.swing.JSpinner txtDiasMantem;
    private javax.swing.JTextField txtExecutaAntes;
    private javax.swing.JTextField txtExecutaDepois;
    // End of variables declaration//GEN-END:variables
}
