/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package backup.dats;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author fernando
 */
public class FrmPost extends javax.swing.JFrame {

    /**
     * Creates new form FrmPost
     */
    Log logger;

    public FrmPost() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtCaminhoBin = new javax.swing.JTextField();
        btLoadExecutaAntes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDatabase = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPorta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtServidor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btTesta = new javax.swing.JButton();
        txtDatabaseEdoc = new javax.swing.JTextField();
        btTestaEdoc = new javax.swing.JButton();
        ckEdoc = new javax.swing.JCheckBox();
        ckMakito = new javax.swing.JCheckBox();
        btSalvaConfig = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados PostgreSQL"));

        txtCaminhoBin.setText("C:\\Program Files (x86)\\PostgreSQL\\9.3\\bin");

        btLoadExecutaAntes.setText("Selecionar");
        btLoadExecutaAntes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoadExecutaAntesActionPerformed(evt);
            }
        });

        jLabel1.setText("Caminho da pasta Bin");

        jLabel2.setText("Usuário");

        txtUsuario.setText("postgres");

        jLabel4.setText("Database");

        txtDatabase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDatabaseKeyTyped(evt);
            }
        });

        jLabel5.setText("Porta");

        txtPorta.setText("5432");

        jLabel6.setText("Servidor");

        txtServidor.setText("localhost");

        jLabel3.setText("Senha");

        txtSenha.setText("postgres");

        btTesta.setText("Testar");
        btTesta.setEnabled(false);
        btTesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTestaActionPerformed(evt);
            }
        });

        txtDatabaseEdoc.setText("ManagerEDoc");
        txtDatabaseEdoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDatabaseEdocKeyTyped(evt);
            }
        });

        btTestaEdoc.setText("Testar");
        btTestaEdoc.setEnabled(false);
        btTestaEdoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTestaEdocActionPerformed(evt);
            }
        });

        ckEdoc.setText("Backup E-doc Local");
        ckEdoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckEdocMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ckEdocMouseReleased(evt);
            }
        });
        ckEdoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckEdocActionPerformed(evt);
            }
        });

        ckMakito.setText("Backup Makito");
        ckMakito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckMakitoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ckMakitoMouseReleased(evt);
            }
        });
        ckMakito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckMakitoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCaminhoBin, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btLoadExecutaAntes))
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtServidor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(ckMakito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btTesta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ckEdoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDatabaseEdoc, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btTestaEdoc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCaminhoBin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLoadExecutaAntes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)))
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTesta)
                    .addComponent(ckMakito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatabaseEdoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckEdoc)
                    .addComponent(btTestaEdoc))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btSalvaConfig.setBackground(new java.awt.Color(1, 109, 187));
        btSalvaConfig.setForeground(new java.awt.Color(255, 255, 255));
        btSalvaConfig.setText("Salvar configurações");
        btSalvaConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvaConfigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvaConfig)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSalvaConfig)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLoadExecutaAntesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoadExecutaAntesActionPerformed
        // TODO add your handling code here:
        JFileChooser j = new JFileChooser(new File("C:"));
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        j.setDialogTitle("Selecionar pasta Bin do PostgreSQL");
        j.setApproveButtonText("Selecionar");
        j.setAcceptAllFileFilterUsed(false);
        Integer opt = j.showSaveDialog(this);
        if (opt == 0) {
            txtCaminhoBin.setText(j.getSelectedFile().getAbsolutePath());
        }

    }//GEN-LAST:event_btLoadExecutaAntesActionPerformed

    private void btSalvaConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvaConfigActionPerformed
        try {
            // TODO add your handling code here:
            Configuracoes cfg = new Configuracoes();
            cfg.setPropriedade("caminho_post", txtCaminhoBin.getText());
            cfg.setPropriedade("servidor_post", txtServidor.getText());
            cfg.setPropriedade("porta_post", txtPorta.getText());
            cfg.setPropriedade("usuario_post", txtUsuario.getText());
            cfg.setPropriedade("senha_post", String.valueOf(txtSenha.getPassword()));
            cfg.setPropriedade("banco_post", txtDatabase.getText());
            cfg.setPropriedade("makitoPost_backup", String.valueOf(ckMakito.isSelected()));
            cfg.setPropriedade("edoc_backup", String.valueOf(ckEdoc.isSelected()));
            cfg.setPropriedade("banco_edoc", txtDatabaseEdoc.getText());
            setVisible(false);
        } catch (UnsupportedEncodingException ex) {
            logger.erro(ex.getMessage());
        } catch (IOException ex) {
            logger.erro(ex.getMessage());
        }
    }//GEN-LAST:event_btSalvaConfigActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            logger = new Log();
            Configuracoes cfg = new Configuracoes();
            txtCaminhoBin.setText(cfg.getPropriedade("caminho_post"));
            txtServidor.setText(cfg.getPropriedade("servidor_post"));
            txtPorta.setText(cfg.getPropriedade("porta_post"));
            txtUsuario.setText(cfg.getPropriedade("usuario_post"));
            txtSenha.setText(cfg.getPropriedade("senha_post"));
            txtDatabase.setText(cfg.getPropriedade("banco_post"));
            txtDatabaseEdoc.setText(cfg.getPropriedade("banco_edoc"));
            ckEdoc.setSelected(Boolean.valueOf(cfg.getPropriedade("edoc_backup")));
            ckMakito.setSelected(Boolean.valueOf(cfg.getPropriedade("makitoPost_backup")));
            btTesta.setEnabled(ckMakito.isSelected() && !txtDatabase.getText().equals(""));
            btTestaEdoc.setEnabled(ckEdoc.isSelected() && !txtDatabaseEdoc.getText().equals(""));
        } catch (UnsupportedEncodingException ex) {
            logger.erro(ex.getMessage());
        } catch (IOException ex) {
            logger.erro(ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void btTestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTestaActionPerformed
        confereConexao("SLCFIL", false);
    }//GEN-LAST:event_btTestaActionPerformed

    private void ckEdocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckEdocMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ckEdocMouseClicked

    private void ckEdocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckEdocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckEdocActionPerformed

    private void txtDatabaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatabaseKeyTyped
        // TODO add your handling code here:
        btTesta.setEnabled(!txtDatabase.getText().equals(""));

    }//GEN-LAST:event_txtDatabaseKeyTyped

    private void btTestaEdocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTestaEdocActionPerformed
       
        confereConexao("*", true);
    }//GEN-LAST:event_btTestaEdocActionPerformed

    private void ckMakitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckMakitoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ckMakitoMouseClicked

    private void ckMakitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckMakitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckMakitoActionPerformed

    private void txtDatabaseEdocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatabaseEdocKeyTyped
        // TODO add your handling code here:
         btTestaEdoc.setEnabled(!txtDatabaseEdoc.getText().equals(""));
    }//GEN-LAST:event_txtDatabaseEdocKeyTyped

    private void ckMakitoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckMakitoMouseReleased
         btTesta.setEnabled(ckMakito.isSelected() && !txtDatabase.getText().equals(""));
    }//GEN-LAST:event_ckMakitoMouseReleased

    private void ckEdocMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckEdocMouseReleased
        // TODO add your handling code here:
         btTestaEdoc.setEnabled(ckEdoc.isSelected() && !txtDatabaseEdoc.getText().equals(""));
    }//GEN-LAST:event_ckEdocMouseReleased

    private void confereConexao(String tabela, boolean edoc) {
            String database, arquivoTeste;
        arquivoTeste = System.getProperty("java.io.tmpdir")+"testePostgres.backup";
        if (new File(txtCaminhoBin.getText() + "\\pg_dump.exe").exists()) {
            try {
                if (!edoc) {
                    database = txtDatabase.getText();
                } else {
                    database = "ManagerEDoc";
                }
                List<String> comandos = new ArrayList<>();
                logger.info("Testando backup do PostgreSQL, pasta_bin:" + txtCaminhoBin.getText() + " servidor: " + txtServidor.getText() + ":" + txtPorta.getText() + " usuario: " + txtUsuario.getText());
                comandos.add(txtCaminhoBin.getText() + "\\pg_dump.exe");
                comandos.add("-i");
                comandos.add("-h");
                comandos.add(txtServidor.getText());
                comandos.add("-p");
                comandos.add(txtPorta.getText());
                comandos.add("-U");
                comandos.add(txtUsuario.getText());
                comandos.add("-t");
                comandos.add(tabela);
                comandos.add("-F");
                comandos.add("tar");
                comandos.add("-f");
                comandos.add(arquivoTeste);
                comandos.add(database);
                ProcessBuilder builder = new ProcessBuilder(comandos);
                builder.environment().put("PGPASSWORD", String.valueOf(txtSenha.getPassword()));
                builder.redirectErrorStream(true);
                Process p = builder.start();
                BufferedReader r = new BufferedReader(new InputStreamReader(p.getInputStream()));
                String line;
                while (true) {
                    line = r.readLine();
                    if (line == null) {
                        break;
                    }
                    JOptionPane.showMessageDialog(null, database+" - "+tabela+" Ocorreu o seguinte erro: \n" + line + "\n");
                       
                    //apaga arquivo de teste
                    File teste = new File(arquivoTeste);
                    if (teste.exists()) {
                        teste.delete();
                    }
                    return;
                }
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(FrmInicio.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(FrmInicio.class.getName()).log(Level.SEVERE, null, ex);
            }
              
            JOptionPane.showMessageDialog(null, "Tudo ok com a conexão PostgreSQL!");
            logger.info("As configurações do PostgresSQL estão corretas");
        } else {
            JOptionPane.showMessageDialog(null, "Não foi possivel encontrar o arquivo pg_dump.exe em:\n" + txtCaminhoBin.getText());   
        }
        //apaga arquivo de teste
        File teste = new File(arquivoTeste);
        if (teste.exists()) {
            teste.delete();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLoadExecutaAntes;
    private javax.swing.JButton btSalvaConfig;
    private javax.swing.JButton btTesta;
    private javax.swing.JButton btTestaEdoc;
    private javax.swing.JCheckBox ckEdoc;
    private javax.swing.JCheckBox ckMakito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCaminhoBin;
    private javax.swing.JTextField txtDatabase;
    private javax.swing.JTextField txtDatabaseEdoc;
    private javax.swing.JTextField txtPorta;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtServidor;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
